 

FROM python:3.8-slim
 
WORKDIR /app
COPY . .
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt
 
EXPOSE 80 
CMD ["python", "-m", "src.app.start-fastapi"]

# EXPOSE 5000
# CMD ["python", "./flask-app.py"]

