name: Build and Deploy
on: 
  pull_request:
    branches: ['dev', 'qas', 'stg', 'prd']

env:
  GH_REPO   : Bineo2/data-prod-catalogs
  DKR_IMAGE : prod-catalogs-webapp
  DKR_TAG   : '1.0.38'
  # ACR_HOST  -> init.outputs.registry
  # AZURE_WEB -> init.outputs.app-name 

jobs:
  init: 
    runs-on: ubuntu-latest
    outputs: 
      env-branch : ${{steps.set-variables.outputs.env-branch}}
      app-name   : ${{steps.set-variables.outputs.app-name}}
      reg-user   : ${{steps.set-variables.outputs.reg-user}} 
  
    steps: 
      - name : Set Variables
        id   : set-variables
        run  : |
          case ${GITHUB_BASE_REF##*/} in
            "dev") 
              echo "::set-output name=env-branch::dev"
              echo "::set-output name=reg-user::prodcatalogsregistry"
              echo "::set-output name=app-name::wap-prod-catalogs-dev"
              ;;
            "qas")
              echo "::set-output name=env-branch::qas"
              echo "::set-output name=reg-user::acrCrossChannelDataQas"
              echo "::set-output name=app-name::as-catalogs-data-qas"
              ;;
            "stg")
              echo "::set-output name=env-branch::stg"
              echo "::set-output name=reg-user::acrCrossChannelDataQas"
              echo "::set-output name=app-name::as-catalogs-adm-stg"
              ;;
          esac

  build-and-deploy :     
    runs-on     : ubuntu-latest
    needs       : init
    environment : ${{needs.init.outputs.env-branch}}
    
    steps : 
    # https://github.com/actions/checkout
    - name : Checkout GitHub Actions 
      uses : actions/checkout@v2
      with : 
        repository : ${{env.GH_REPO}}
        ref        : ${{needs.init.outputs.env-branch}}

    # https://github.com/mr-smithers-excellent/docker-build-push
    - name : Build and push container image to registry
      id   : container-registry
      uses : mr-smithers-excellent/docker-build-push@v5.5
      with : 
        dockerfile : dockerfile.ci 
        image      : ${{env.DKR_IMAGE}}
        tags       : ${{env.DKR_TAG}}
        username   : ${{needs.init.outputs.reg-user}}
        password   : ${{secrets.ACR_PASS}}
        registry   : '${{needs.init.outputs.reg-user}}.azurecr.io'
        buildArgs  : 'SERVER_TYPE=wap,ENV_TYPE=${{needs.init.outputs.environment}}'
    
    # https://github.com/Azure/webapps-deploy
    - name : Deploy to App Service
      uses : azure/webapps-deploy@v2
      with :
        images         : '${{needs.init.outputs.reg-user}}.azurecr.io/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}'
        app-name       :  ${{needs.init.outputs.app-name}}
        publish-profile : ${{secrets.WAP_PUBLISH}}
        
     