name: Build and Deploy
on: 
  workflow_dispatch:
    inputs:
      deploy_to:
        description:  Github environment contains secrets about its corresponding Azure counterpart.
        required: true
        type: choice
        options: 
          - prd
          - stg
          - qas 
          - dev
          - drp

env :
  GH_REPO    : Bineo2/data-prod-catalogs
  DKR_IMAGE  : prod-catalogs-webapp
  DKR_TAG    : '1.0.84'   # Ajustar VALIDATE_DOCKERFILE también. 

jobs :
  build-and-deploy :     
    runs-on     : ubuntu-latest
    environment : ${{github.event.inputs.deploy_to}}
    steps : 
      - name : Set Variables
        id   : set-variables   
        run  : |
          case ${{github.event.inputs.deploy_to}} in
            "prd")
              echo "WAP_NAME=as-catalogs-data-prd"  >> $GITHUB_ENV;;
            "drp")
              echo "WAP_NAME=as-catalogs-data-drp"  >> $GITHUB_ENV;;
            "stg")
              echo "WAP_NAME=as-catalogs-adm-stg"   >> $GITHUB_ENV;;
            "qas")
              echo "WAP_NAME=as-catalogs-data-qas"  >> $GITHUB_ENV;;
            "dev")
              echo "WAP_NAME=wap-prod-catalogs-dev" >> $GITHUB_ENV;;
          esac
      # https:/:/github.com/actions/checkout
      - name : Checkout GitHub Actions
        uses : actions/checkout@v2
        with : 
          repository : ${{env.GH_REPO}}  
      # https://github.com/mr-smithers-excellent/docker-build-push
      - name : Build and push container image to registry
        id   : container-registry
        uses : mr-smithers-excellent/docker-build-push@v5.5
        with : 
          registry   : ${{secrets.ACR_HOST}}
          username   : ${{secrets.ACR_USER}}
          password   : ${{secrets.ACR_PASS}}
          image      : ${{env.DKR_IMAGE}}
          tags       : ${{env.DKR_TAG}}-${{github.event.inputs.deploy_to}}
          dockerfile : dockerfile.ci 
          buildArgs  : ENV_TYPE=${{github.event.inputs.deploy_to}},SERVER_TYPE=wap
      # https://github.com/Azure/webapps-deploy
      - name : Deploy to App Service
        uses : azure/webapps-deploy@v2
        with :
          images :  ${{secrets.ACR_HOST}}/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}-${{github.event.inputs.deploy_to}}
          app-name : ${{env.WAP_NAME}}
          publish-profile : ${{secrets.WAP_PUBLISH}}
      
      - name: Trigger Disaster Recovery 
        if: github.event.inputs.deploy_to == 'prd'
        uses: ./.github/workflows/build_deploy.yml
        with: 
          deploy_to: drp
        
