name: Compile Dockerfile
on: 
  pull_request:
    branches: ['dev', 'qas', 'stg', 'prd']

env:
  GH_REPO   : Bineo2/data-prod-catalogs
  DKR_IMAGE : prod-catalogs-webapp
  DKR_TAG   : '1.0.391'

jobs:
  init: 
    runs-on: ubuntu-latest
    outputs: 
      env-branch : ${{steps.set-variables.outputs.env-branch}}
      app-name   : ${{steps.set-variables.outputs.app-name}}
  
    steps: 
      - name : Set Variables
        id   : set-variables
        run  : |
          case ${GITHUB_BASE_REF} in
            "dev") 
              echo "::set-output name=env-branch::dev"
              echo "::set-output name=app-name::wap-prod-catalogs-dev"
              ;;
            "qas")
              echo "::set-output name=env-branch::qas"
              echo "::set-output name=app-name::as-catalogs-data-qas"
              ;;
            "stg")
              echo "::set-output name=env-branch::stg"
              echo "::set-output name=app-name::as-catalogs-adm-stg"
              ;;
          esac

  build :     
    runs-on     : ubuntu-latest
    needs       : init
    environment : ${{needs.init.outputs.env-branch}}
    
    steps : 
    # https:/:/github.com/actions/checkout
    - name : Checkout GitHub Actions 
      uses : actions/checkout@v2
      with : 
        ref        : ${{github.ref}}
        repository : ${{env.GH_REPO}}

    # https://github.com/mr-smithers-excellent/docker-build-push
    - name : Build image
      id   : container-registry
      uses : mr-smithers-excellent/docker-build-push@v5.5
      with : 
        pushImage : false
        dockerfile : dockerfile.ci 
        image      : ${{env.DKR_IMAGE}}
        tags       : ${{env.DKR_TAG}}
        username   : ${{secrets.ACR_USER}}
        password   : ${{secrets.ACR_PASS}}
        registry  : '${{secrets.ACR_USER}}.azurecr.io'
        buildArgs : 'SERVER_TYPE=wap,ENV_TYPE=${{needs.init.outputs.env-branch}}'
