name: Compile Dockerfile
on: 
  pull_request:
    branches: ['dev', 'qas', 'stg', 'prd', 'drp']

env:
  GH_REPO   : Bineo2/data-prod-catalogs
  DKR_IMAGE : prod-catalogs-webapp
  DKR_TAG   : '1.0.81'
  BRANCH_ENV : ${{github.base_ref || github.ref_name}}

jobs :
  build :     
    runs-on : ubuntu-latest
    steps : 
    - name : Checkout GitHub Actions 
      uses : actions/checkout@v2
      with : 
        repository : ${{env.GH_REPO}}
        ref        : ${{env.BRANCH_ENV}}
    # https://github.com/mr-smithers-excellent/docker-build-push
    - name : Build image
      id   : container-registry
      uses : mr-smithers-excellent/docker-build-push@v5.8
      with : 
        pushImage : false
        dockerfile : dockerfile.ci 
        image      : ${{env.DKR_IMAGE}}
        tags       : ${{env.DKR_TAG}}-${{env.BRANCH_ENV}}
        username   : 'dummy'
        password   : 'dummy'
        registry   : 'dummy'
        buildArgs  : 'SERVER_TYPE=wap,ENV_TYPE=${{env.BRANCH_ENV}}'
